stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.10-slim-buster
  script:
    - pytest

build_image:
  stage: build
  image: docker:20.10.22
  services:
    - docker:20.10.22-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: "ppyzel/zgdk"
    IMAGE_TAG: "0.1"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build --build-arg QEMU_ARCH=aarch64 --build-arg QEMU_LD_PREFIX=/usr/aarch64-linux-gnu -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  tags:
    - aarch64-runner

deploy_to_server:
  stage: deploy
  image: ubuntu:20.04
  script:
    - ssh -o "StrictHostKeyChecking=no" ubuntu@138.3.245.125 "cd Projects/zgdk && docker pull ppyzel/zgdk:0.1 && docker run -d -e ZAGADKA_TOKEN=${ZAGADKA_TOKEN} ppyzel/zgdk:0.1"
  only:
    - main
