stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.10-slim-buster
  before_script:
    - apt-get update -qq && apt-get install -y 
    - pip install -r requirements.txt
  script:
    - pytest

build_image:
  stage: build
  image: docker:20.10.22
  services:
    - arm64v8/docker:20.10.22-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: "ppyzel/zgdk"
    IMAGE_TAG: "0.1"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build --build-arg QEMU_ARCH=aarch64 --build-arg QEMU_LD_PREFIX=/usr/aarch64-linux-gnu -t aarch64/python:3.10 .
    - docker tag aarch64/python:3.10 $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_to_server:
  stage: deploy
  image: ubuntu:20.04
  services:
    - arm64v8/docker:20.10.22-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apt-get update -qq && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - cat "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - ssh -o "StrictHostKeyChecking=no" ubuntu@138.3.245.125 "cd Projects/zgdk && docker pull ppyzel/zgdk:0.1 && docker run -d -e ZAGADKA_TOKEN=${ZAGADKA_TOKEN} --platform=linux/aarch64 ppyzel/zgdk:0.1"
  only:
    - main
