version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python main.py
    environment:
      - ZAGADKA_TOKEN=${ZAGADKA_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIPO_API_TOKEN=${TIPO_API_TOKEN}
    ports:
      - 8000:8000
    platform: linux/arm64
    depends_on:
      - db
    volumes:
      # Mount source code for development (hot reload)
      - ./main.py:/app/main.py
      - ./cogs:/app/cogs
      - ./utils:/app/utils
      - ./datasources:/app/datasources
      - ./config.yml:/app/config.yml
    restart: unless-stopped

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # Separate logs volume for development
      - db-logs:/var/log/postgresql
    command: [
      "postgres", 
      "-c", "logging_collector=on", 
      "-c", "log_directory=/var/log/postgresql",
      "-c", "log_filename=postgresql-%Y-%m-%d.log",
      "-c", "log_min_messages=warning",
      "-c", "log_rotation_age=1d",
      "-c", "log_truncate_on_rotation=on"
    ]
    restart: unless-stopped

volumes:
  db-data:
  db-logs: 