version: "3.9"
services:
  app:
    image: ppyzel/zgdk:0.1
    command: python main.py
    environment:
      - ZAGADKA_TOKEN=${ZAGADKA_TOKEN}
    ports:
      - 8000:8000
    platform: linux/arm64
    depends_on:
      - db

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
