version: "3.9"
services:
  app:
    # image: ppyzel/zgdk:0.1
    build: .
    command: python main.py
    environment:
      - ZAGADKA_TOKEN=${ZAGADKA_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIPO_API_TOKEN=${TIPO_API_TOKEN}
    ports:
      - 8000:8000
    platform: linux/arm64
    depends_on:
      - db

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pg_log:/var/lib/postgresql/data/pg_log
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_min_messages=warning", "-c", "log_directory=pg_log", "-c", "log_filename=postgresql-%Y-%m-%d.log"]

volumes:
  db-data:
