version: '3.8'

services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: zgdk_monitor
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ./monitoring:/app/monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - zgdk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/monitoring/status.json') else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3

  status-server:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: zgdk_status_server
    command: python monitoring/status_server.py 8888
    ports:
      - "8888:8888"
    volumes:
      - ./monitoring:/app/monitoring:ro
    networks:
      - zgdk_network
    restart: unless-stopped
    depends_on:
      - monitor

networks:
  zgdk_network:
    external: true