monitoring:
  interval_seconds: 300  # Check every 5 minutes
  timeout_seconds: 30
  retry_attempts: 3

github:
  owner: "your-github-username"  # UPDATE THIS
  repo: "zgdk"
  workflows:
    - "ci"
    - "docker-build"
    - "test"

docker:
  containers:
    - "zgdk_app_1"
    - "zgdk_db_1"
    - "zgdk_redis_1"
  compose_file: "docker-compose.yml"

argocd:
  enabled: false  # Enable if using ArgoCD
  server: "argocd.example.com"
  app_name: "zgdk"
  namespace: "default"

notifications:
  webhook_url: ""  # Add Slack/Discord webhook URL here
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    from_email: "monitoring@example.com"
    to_emails:
      - "admin@example.com"

status_page:
  output_path: "monitoring/status.html"
  update_interval: 60  # Update page every minute

alerts:
  consecutive_failures: 3  # Alert after 3 consecutive failures
  recovery_notification: true  # Notify when service recovers