apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-discord-bot
  labels:
    app: {{ .Release.Name }}
    component: discord-bot
spec:
  type: ClusterIP
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: health
  selector:
    app: {{ .Release.Name }}
    component: discord-bot