apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agents
  labels:
    app: ai-agents
    component: ai-processing
spec:
  replicas: 3  # Scale based on load
  selector:
    matchLabels:
      app: ai-agents
  template:
    metadata:
      labels:
        app: ai-agents
        version: "1.0"
    spec:
      containers:
      - name: ai-agent
        image: zgdk/ai-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: AGENT_TYPE
          value: "general"
        - name: MODEL_PROVIDER
          value: "gemini"
        - name: REDIS_HOST
          value: "redis-service"
        envFrom:
        - secretRef:
            name: ai-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agents-service
spec:
  selector:
    app: ai-agents
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-agents-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-agents
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80