apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgdk-bot
  labels:
    app: zgdk-bot
    component: discord-bot
spec:
  replicas: 1  # Discord bot should have only 1 replica per token
  selector:
    matchLabels:
      app: zgdk-bot
  template:
    metadata:
      labels:
        app: zgdk-bot
        version: "1.0"
    spec:
      containers:
      - name: bot
        image: zgdk/bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8089  # API port
        - containerPort: 8090  # Metrics port
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: DEV_MODE
          value: "false"
        - name: ENABLE_MCP
          value: "true"
        envFrom:
        - secretRef:
            name: zgdk-secrets
        - configMapRef:
            name: zgdk-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: zgdk-bot-service
spec:
  selector:
    app: zgdk-bot
  ports:
  - name: api
    port: 8089
    targetPort: 8089
  - name: metrics
    port: 8090
    targetPort: 8090