apiVersion: v1
kind: ConfigMap
metadata:
  name: zgdk-config
data:
  database.name: "zagadka"
  database.pool_size: "10"
  log.level: "INFO"
  bot.prefix: ","
  bot.status: "zaGadka bot"
  ai.cache_ttl: "3600"
  ai.max_retries: "3"